server:
  port: 8080
  context-path: /helloBoot
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.154.150:3306/demo?useUnicode=true&characterEncoding=utf8
    maxActive: 30
    maxWait: 300000
    validationQuery: select 1
    username: root
    password: Huawei123#

mybatis:
  typeAliasesPackage: springboot.model
  mapperLocations: classpath:mapper/*.xml